-- SQL Dump of Ziraf03_be.accdb
-- generated by MDB Viewer 2.2.5
-- optimized for MySQL

SET NAMES 'UTF8';



DROP TABLE IF EXISTS `tblAnnee`;

CREATE TABLE `tblAnnee` (
    `An_Code` INTEGER PRIMARY KEY,
    `An_Annee` INTEGER
) CHARACTER SET 'UTF8';

INSERT INTO `tblAnnee`(`An_Code`,`An_Annee`)
VALUES(5,2012),
      (6,2013);


