-- SQL Dump of Ziraf03_be.accdb
-- generated by MDB Viewer 2.2.5
-- optimized for MySQL

SET NAMES 'UTF8';



DROP TABLE IF EXISTS `tblLogPos`;

CREATE TABLE `tblLogPos` (
    `Lf_Code` INTEGER PRIMARY KEY,
    `Lf_Alias` VARCHAR(50),
    `Lf_AliasCode` INTEGER,
    `Lf_Creation` DATETIME,
    `Lf_Modif` DATETIME,
    `Lf_User` VARCHAR(25)
) CHARACTER SET 'UTF8';

INSERT INTO `tblLogPos`(`Lf_Code`,`Lf_Alias`,`Lf_AliasCode`,`Lf_Creation`,`Lf_Modif`,`Lf_User`)
VALUES(4,'tblMain',21,'2009-11-05 16:16:11','2009-11-05 16:16:11','Admin'),
      (5,'tblMain10',440,'2009-11-13 15:29:11','2009-11-13 15:29:11','Admin'),
      (6,'tblMain20',920,'2009-11-13 15:29:22','2009-11-13 15:29:22','Admin'),
      (7,'tblClientPeriodes',94237,'2009-11-13 15:48:00','2009-11-13 15:48:00','Admin'),
      (8,'tblProduit',1,'2009-11-24 15:29:14','2009-11-24 15:29:14','Admin'),
      (9,'tblCpe',1100,'2009-11-24 16:00:18','2009-11-24 16:00:18','Admin'),
      (10,'tblClient',2614,'2009-11-26 14:10:33','2009-11-26 14:10:33','Admin'),
      (11,'tblPaiement',3,'2009-11-26 15:03:45','2009-11-26 15:03:45','Admin');


