-- SQL Dump of Ziraf03_be.accdb
-- generated by MDB Viewer 2.2.5
-- optimized for MySQL

SET NAMES 'UTF8';



DROP TABLE IF EXISTS `tblMois`;

CREATE TABLE `tblMois` (
    `Mo_Code` INTEGER PRIMARY KEY,
    `Mo_Desc` VARCHAR(15),
    `Mo_Abbrev` VARCHAR(10),
    `Mo_Tri` INTEGER
) CHARACTER SET 'UTF8';

INSERT INTO `tblMois`(`Mo_Code`,`Mo_Desc`,`Mo_Abbrev`,`Mo_Tri`)
VALUES(1,'Janvier','Jan.',10),
      (2,'Février','Fév.',15),
      (3,'Mars','Mars',20),
      (4,'Avril','Avril',25),
      (5,'Mai','Mai',30),
      (6,'Juin','Juin',35),
      (7,'Juillet','Juil.',40),
      (8,'Août','Août',45),
      (9,'Septembre','Sept.',50),
      (10,'Octobre','Oct.',55),
      (11,'Novembre','Nov.',60),
      (12,'Décembre','Déc.',65);


