-- SQL Dump of Ziraf03_be.accdb
-- generated by MDB Viewer 2.2.5
-- optimized for MySQL

SET NAMES 'UTF8';



DROP TABLE IF EXISTS `tblPaiement`;

CREATE TABLE `tblPaiement` (
    `Py_Code` INTEGER PRIMARY KEY,
    `Py_Desc` VARCHAR(50),
    `Py_Abbrev` VARCHAR(10),
    `Py_Tri` INTEGER
) CHARACTER SET 'UTF8';

INSERT INTO `tblPaiement`(`Py_Code`,`Py_Desc`,`Py_Abbrev`,`Py_Tri`)
VALUES(1,'Carte Credit','cc',10),
      (2,'Chèques','E',20),
      (3,'Autre','ot',30);


